### ISSUE TITLE
`persistQuery` option doesn't work

### ISSUE THREAD

**Issue by jakewisse** [FormidableLabs/redux-little-router#172]
It looks like the `persistQuery` option was first implemented [in the `Link` component](https://github.com/FormidableLabs/redux-little-router/blob/da3d3156aed6d25ae63c65895a1c79e78cb524bb/src/components/link.js#L26-L49) through referencing the existing state in the Redux store, but then later it was copied over to the reducer. However, I don't know how this was supposed to work since the middleware will call the `history` lib's `push()` function with the given `search` (updating the URL with the new query [empty or otherwise], wiping out the previous one), way before the data flow reaches the reducer.

It seems to me that the only way to resolve this for all possible implementations of the history API is to produce the actions module in `install()` which has the desired history impl. injected into it. Then, we could do the query merging<sup>1</sup> up front by referencing the state in `history.state`.

--
1: FWIW, when working on this it wasn't clear to me in the README whether `persistQuery` would merge the two queries (see #132), or if it would simply not throw away the previous one if not specifying a `pathname`.

**Comment by drKnoxy** [comment]
@tptee if you can guide a solution to this i'll get a PR submitted.

**Comment by tptee** [comment]
Fixed in `v14.0.0-1`. Real release coming soon!

**Comment by tptee** [comment]
Fixed in `v14.0.0-1`. Real release coming soon!

**Comment by jakewisse** [comment]
Thanks @tptee! While this looks great for `<Link>`s, the `persistQuery` option should still not work for manually dispatching `push()`, correct?

**Comment by adamesque** [comment]
Although the merged PR does include reducer code, `persistQuery` doesn't appear to work for `push()` in our project. I'll see if I can create a reduction & then file a new issue.
