### ISSUE TITLE
Nested RelativeFragments not working as expected

### ISSUE THREAD

**Issue by mariusk** [FormidableLabs/redux-little-router#80]
I'm trying to migrate some code from `react-router` to `redux-little-router`, but I'm struggling a bit with how `Fragments` are supposed to work. I think I've narrowed it down to this (which can be added to `fragment.spec.js` in the `test` directory):

````javascript
  it('does support traditional nesting', () => {
    const wrapper = mount(
      <RelativeFragment forRoute='/play'>
        <RelativeFragment forRoute='/c/:code'>
          <p>code</p>
        </RelativeFragment>
        <RelativeFragment forRoute='/'>
          <p>none</p>
        </RelativeFragment>
      </RelativeFragment>,
      fakeContext({
        pathname: '/play/c/123',
        route: '/play/c/:code'
      })
    );

    expect(wrapper.containsMatchingElement(<p>code</p>)).to.be.true;
    expect(wrapper.containsMatchingElement(<p>none</p>)).to.be.false;
});
````

So could anyone clue me in on how this is supposed to work, why isn't the Fragment containing "code" being matched?

**Comment by tptee** [comment]
It's a big ol' 🐜 (see #76). Hoping to have a fix in this evening

**Comment by tptee** [comment]
Fixed in `v9.0.3`!

**Comment by mariusk** [comment]
It's still not working "as expected" at my end. In the original example, the test checking for "none" fails (it exists when it should not). I've added an additional test case which checks the opposite action (the "fallthrough" or "default route"). It fails as well. It may very well be that I'm not reading the right docs, or that the Fragment features is no real substitute for react-router's Route yet. I'll share the updated tests here and make a PR for them, in case you feel such features really should work (and if so, please clue me in!).

````javascript
  it('does support traditional nesting', () => {
    const wrapper = mount(
      <RelativeFragment forRoute='/play'>
        <RelativeFragment forRoute='/c/:code'>
          <p>code</p>
        </RelativeFragment>
        <RelativeFragment forRoute=''>
          <p>none</p>
        </RelativeFragment>
      </RelativeFragment>,
      fakeContext({
        pathname: '/play/c/123',
        route: '/play/c/:code'
      })
    );

    expect(wrapper.containsMatchingElement(<p>code</p>)).to.be.true;
    expect(wrapper.containsMatchingElement(<p>none</p>)).to.be.false;
  });
  
  it('does support default route', () => {
    const wrapper = mount(
      <RelativeFragment forRoute='/play'>
        <RelativeFragment forRoute='/c/:code'>
          <p>code</p>
        </RelativeFragment>
        <RelativeFragment forRoute='/'>
          <p>none</p>
        </RelativeFragment>
      </RelativeFragment>,
      fakeContext({
        pathname: '/play',
        route: '/play'
      })
    );

    expect(wrapper.containsMatchingElement(<p>code</p>)).to.be.false;
    expect(wrapper.containsMatchingElement(<p>none</p>)).to.be.true;
  });
````

**Comment by tptee** [comment]
Those above tests _should_ fail, at least under the current design.

`<Fragment>` is _not_ a substitute for `<Route>`. They're different components with different goals. `<Fragment>` is not designed to be a rigid switchboard; it was born from the requirements of unconventional, split-pane UIs in client work.

That said, your use case is valid and common, and I'd love it if you could put in an enhancement request for:

- "index" routes
- eagerly-matched fragments (i.e. only display the fragment that matches

I'll put some thought into what the API would look like for both features.

Side note: `forRoute=''` is undocumented and has essentially undefined behavior. Wouldn't rely on it 😉

**Comment by mariusk** [comment]
Yes, I've figured as much the last couple of days. Until it actually has a minimal feature set matching some of the typical things people use react-router for it may be worth warning people about this. From reading the blog posts and front page of this repo, I had the impression that I could use it instead of react-router, which I now know is wrong. At least for the time being. :-)

**Comment by tptee** [comment]
Sorry it didn't work out for you. I don't believe we've been misleading. RelativeFragment is barely two weeks old, so have some understanding that there's more to be done and that this takes time.

**Comment by mariusk** [comment]
No worries, I just bought into the argument that react-router needs a replacement and wanted to give it a try. I'll keep trying, because the argument is still valid.

**Comment by tptee** [comment]
This behavior ("greedy" matching) got merged in #108 and release in `v12.0.0` if you want to check it out!
